title: Blockchain Guidelines
description: SpaceDev's Blockchain Guidelines. All theoretical and practical blockchain knowledge!
theme: just-the-docs
# favicon_ico: /assets/images/SpaceDev_logo.svg

url: https://just-the-docs.github.io

search_enabled: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
